/*Copyright (c) 2015-2016 WaveMaker.com All Rights Reserved.
 This software is the confidential and proprietary information of WaveMaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with WaveMaker.com*/

package com.wavemaker.sampleapps.wavekart.eshopping.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.List;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.wavemaker.sampleapps.wavekart.eshopping.models.query.*;

public interface EshoppingQueryExecutorService {

    Page<TotalItemsPriceCartProdResponse> executeTotalItemsPrice_CartProd(Integer cartId, Pageable pageable);

    Downloadable exportTotalItemsPrice_CartProd(ExportType exportType, Integer cartId, Pageable pageable);

    Page<TotalItemsPriceOrdersResponse> executeTotalItemsPrice_Orders(Integer oid, Pageable pageable);

    Downloadable exportTotalItemsPrice_Orders(ExportType exportType, Integer oid, Pageable pageable);

    Integer executeDeleteCartItems_LoggedUser(Integer loggedUserCartId);

    Page<GetCartIdByUseridResponse> executeGet_CartIdByUserid(Pageable pageable);

    Downloadable exportGet_CartIdByUserid(ExportType exportType, Pageable pageable);

    Page<MyCartItemsCountResponse> executeMyCart_Items_Count(Pageable pageable);

    Downloadable exportMyCart_Items_Count(ExportType exportType, Pageable pageable);

    Page<QvGetInventoryDetailsResponse> executeQV_getInventoryDetails(List<Integer> productIds, Pageable pageable);

    Downloadable exportQV_getInventoryDetails(ExportType exportType, List<Integer> productIds, Pageable pageable);

    Page<GetCartItemsIdResponse> executeGet_CartItems_id(Integer cid, Pageable pageable);

    Downloadable exportGet_CartItems_id(ExportType exportType, Integer cid, Pageable pageable);

    Integer executeQV_UpdateQuantityFromPI(QvUpdateQuantityFromPiRequest qvUpdateQuantityFromPiRequest);

}


